"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from platform import platform
import dotenv

dotenv.load_dotenv(os.path.join(
    os.path.dirname(os.path.dirname(__file__)), '.env'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000
# SECURITY WARNING: don't run with debug turned on in production!

PLATFORM = os.getenv('PLATFORM')
if PLATFORM == 'DEVELOPMENT':
    DEBUG = True
    ALLOWED_HOSTS = ['*']

elif PLATFORM == 'PRODUCTION':
    DEBUG = True
    ALLOWED_HOSTS = ['fo.gravitycode.me']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'drf_yasg',
    "corsheaders",

    'rest_framework',
    'Main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]
CORS_ALLOWED_ORIGINS = [
    'https://fo.gravitycode.me',
    'http://44.201.165.150:5000',
    'https://fobook.gravitycode.me',
    'http://localhost:3001'
]

CSRF_TRUSTED_ORIGINS = [
    'https://fo.gravitycode.me',
    'http://localhost:3001'
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {

        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'USER:': os.environ.get('PGUSER'),

        'PASSWORD': os.environ.get('PGPASSWORD'),

        'HOST': os.environ.get('PGHOST'),

        'PORT': os.environ.get('PGPORT'),

        'NAME': os.environ.get('PGDATABASE'),

    }

}


REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SQUARE_API_URL = os.environ.get('SQUARE_API_URL')
SQUARE_API_KEY = os.environ.get('SQUARE_API_KEY')


BOOKEO_API_URL = os.environ.get('BOOKEO_API_URL')
BOOKEO_API_KEY = os.environ.get('BOOKEO_API_KEY')
BOOKEO_API_SECRET = os.environ.get('BOOKEO_API_SECRET')

ZOHO_ACCESS_KEY = os.environ.get('ZOHO_ACCESS_KEY')
ZOHO_ENV_ID = os.environ.get('ZOHO_ENV_ID')
ZOHO_DOMAIN_URL = os.environ.get('ZOHO_DOMAIN_URL')
ZOHO_REFRESH_TOKEN = os.environ.get('ZOHO_REFRESH_TOKEN')
ZOHO_CLIENT_ID = os.environ.get('ZOHO_CLIENT_ID')
ZOHO_CLIENT_SECRET = os.environ.get('ZOHO_CLIENT_SECRET')

