version: '3'

services:

  app:
    build: ./backend
    image: "backend-app"
    hostname: "backend-app"
    domainname: "gravity.com"
    container_name: "backend-app"
    tty: true
    stdin_open: true
    networks:
      gravity_default:
        aliases:
          - "app.gravity.com"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/django-static:/usr/src/app/django-static 
      - backend-pips-dir:/usr/local/lib/python3.9/site-packages:delegated
    ports:
      - 5000:5000
    environment:
      VIRTUAL_HOST: "app.gravity.com"
      HOST: "app.gravity.com"
      PORT: 5000
      HISTFILE: /usr/src/app/src/logs/.bash_history.log



    
volumes:
  backend-pips-dir:

networks:
  gravity_default: