# Generated by Django 4.1 on 2026-05-27 20:32

import Main.models.models_sessions
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nick Name')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('min_num', models.IntegerField(blank=True, default=0, null=True)),
                ('max_num', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='GravityUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('cash_amount', models.IntegerField(blank=True, null=True)),
                ('visa_amount', models.IntegerField(blank=True, null=True)),
                ('sub_shift_round', models.IntegerField(blank=True, default=0, null=True)),
                ('json_data', models.JSONField(null=True)),
                ('sub_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_shift_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_shift_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift_money_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift_money_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('actual_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('inventory', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('block_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('block_seats_obj', models.JSONField(blank=True, default=Main.models.models_sessions._default_block_seats, null=True, verbose_name='Block Seats Obj')),
                ('weekday', models.CharField(blank=True, max_length=10, null=True)),
                ('added_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=20, null=True)),
                ('except_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('square_pre', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('json_data', models.JSONField(null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_shift_round', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_cash_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount_visa_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('endshift_page_password', models.CharField(blank=True, default='123', max_length=200, null=True)),
                ('square_team_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('square_location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('current_shift_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_shift_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift_money_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift_money_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('actual_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('inventory', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.JSONField(blank=True, default=dict, null=True)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('bookeo_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('bookeo_secrete', models.CharField(blank=True, max_length=255, null=True)),
                ('options2', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, null=True, size=None)),
                ('square_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('payment', models.JSONField(blank=True, default=dict, null=True)),
                ('number_of_players', models.IntegerField(default=None, null=True)),
                ('type_of_players', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('square_receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('square_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('square_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_sales_receipt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_sales_receipt_num', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('refunded', 'Refunded'), ('hold', 'Hold')], max_length=100, null=True)),
                ('booking_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.customer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Main.session')),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('url', models.TextField()),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='subshifthistory',
            index=models.Index(fields=['sub_shift'], name='subshifthistory_user_idx'),
        ),
        migrations.AddIndex(
            model_name='subshifthistory',
            index=models.Index(fields=['date'], name='subshifthistory_date_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['product', 'start_time'], name='session_product_start_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='session_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['product'], name='schedule_product_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['group'], name='promocode_group_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promocode_code_idx'),
        ),
        migrations.AddIndex(
            model_name='profilehistory',
            index=models.Index(fields=['profile'], name='profilehistory_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='profilehistory',
            index=models.Index(fields=['date'], name='profilehistory_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['group'], name='product_group_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['group'], name='customer_group_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['identifier'], name='customer_identifier_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['session', 'status'], name='booking_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_customer'], name='booking_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['square_receipt_number'], name='booking_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='booking_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['creation_agent'], name='booking_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['timestamp'], name='apilog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['status_code'], name='apilog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['path'], name='apilog_path_idx'),
        ),
    ]
