# Generated by Django 4.1 on 2025-03-07 21:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_group_cash_threshold_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GravityUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('cash_amount', models.IntegerField(blank=True, null=True)),
                ('visa_amount', models.IntegerField(blank=True, null=True)),
                ('sub_shift_round', models.IntegerField(blank=True, default=0, null=True)),
                ('json_data', models.JSONField(null=True)),
                ('sub_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_shift_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_shift_cash', models.FloatField(default=0)),
                ('refund_cash', models.FloatField(default=0)),
                ('refund_visa', models.FloatField(default=0)),
                ('shift_money_cash', models.FloatField(default=0)),
                ('shift_money_visa', models.FloatField(default=0)),
                ('actual_cash', models.FloatField(default=0, null=True)),
                ('actual_visa', models.FloatField(default=0, null=True)),
                ('inventory', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('percentage', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('square_pre', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('json_data', models.JSONField(null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, null=True)),
                ('sub_shift_round', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_cash_limit', models.FloatField(default=0, null=True)),
                ('amount_visa_limit', models.FloatField(default=0, null=True)),
                ('endshift_page_password', models.CharField(blank=True, default='123', max_length=200, null=True)),
                ('square_team_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('square_location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('current_shift_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_shift_cash', models.FloatField(default=0)),
                ('refund_cash', models.FloatField(default=0)),
                ('refund_visa', models.FloatField(default=0)),
                ('shift_money_cash', models.FloatField(default=0)),
                ('shift_money_visa', models.FloatField(default=0)),
                ('actual_cash', models.FloatField(default=0, null=True)),
                ('actual_visa', models.FloatField(default=0, null=True)),
                ('inventory', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.JSONField(blank=True, default=dict, null=True)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('bookeo_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('bookeo_secrete', models.CharField(blank=True, max_length=255, null=True)),
                ('options2', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, null=True, size=None)),
                ('square_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
