# Generated by Django 4.1 on 2024-04-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount_cash_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='amount_visa_limit',
        ),
    ]
