# Generated by Django 4.1 on 2025-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nick Name'),
        ),
    ]
