# Generated by Django 4.1 on 2025-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='block_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
