# Generated by Django 4.1 on 2025-06-25 14:11

import Main.models.models_sessions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='block_seats_obj',
            field=models.JSONField(blank=True, default=Main.models.models_sessions.Session.default_block_seats, null=True),
        ),
    ]
