# Generated by Django 4.1 on 2025-05-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_schedule_session_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weakdays',
            new_name='weakday',
        ),
    ]
