# Generated by Django 4.1 on 2025-05-20 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_product_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 20, 15, 23, 24, 753114), null=True),
        ),
    ]
