# Generated by Django 4.1 on 2025-06-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_session_block_seats_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='block_seats',
        ),
    ]
