# Generated by Django 4.1 on 2025-05-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_session_block_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='all_bookings',
        ),
    ]
