# Generated by Django 4.1 on 2025-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_customer_all_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
