# Generated by Django 4.1 on 2025-05-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_weakdays_schedule_weakday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weakday',
            new_name='weekday',
        ),
    ]
