# Generated by Django 4.1 on 2025-06-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_session_session_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_capacity',
            new_name='added_seats',
        ),
    ]
