# Generated by Django 4.1 on 2025-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_block_seats_obj_session_block_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='block_seats_int',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
