# Generated by Django 4.1 on 2025-05-02 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_weakday_schedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
    ]
