# Generated by Django 4.1 on 2025-05-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('all_bookings', models.ManyToManyField(blank=True, null=True, to='Main.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_customer',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.customer'),
        ),
    ]
