# Generated by Django 4.1 on 2025-05-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_cash_threshold_amount_and_more'),
        ('Main', '0005_remove_booking_customer_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='all_bookings',
            field=models.ManyToManyField(blank=True, to='Main.booking'),
        ),
    ]
