# Generated by Django 4.1 on 2025-05-02 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_schedule_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='except_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None),
        ),
    ]
