# Generated by Django 4.1 on 2025-06-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_session_block_seats_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='block_seats',
        ),
    ]
