# Generated by Django 4.1 on 2025-06-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_session_block_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='block_seats_int',
            new_name='block_seats',
        ),
    ]
