# Generated by Django 4.1 on 2025-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_customer_group_alter_customer_all_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done'), ('refunded', 'Refunded'), ('hold', 'Hold')], max_length=100, null=True),
        ),
    ]
